### ISSUE TITLE
JollaOpas doesn't show map

### ISSUE THREAD

**Issue by hsjpekka** [hsarkanen/JollaOpas#10]
After updating to 0.7.0 route map does not show up anymore. Not even an empty page. Selecting 'Kartta' from the pulley menu doesn't seem to cause any action. 
I have Here WeGo 2.0.10699.

**Comment by hsarkanen** [comment]
Thanks for reporting this. I'll add a note to Openrepos.net that Maps might not work on newer Jolla devices. Jolla 1 is the only device I could test on. If I've understood correctly Here WeGo is Android app and it doesn't have anything to do with maps in native applications. Installing or removing it shouldn't affect map usage in native applications.

I don't know what's Jolla's plan for the future of the maps. It seems that [native Maps is not officially available in the Jolla Store](https://together.jolla.com/question/136988) for Jolla C and Intex Aqua Fish devices. Reasoning why I haven't been able to release JollaOpas to Jolla Store is that QtLocation used for providing maps hasn't stable API in current Qt Framework on Jolla devices. Because of unstable API it's not accepted for Store applications. Jolla is currently using Qt version 5.2 and QtLocation API which provides maps is released as stable in [Qt 5.6](https://wiki.qt.io/New_Features_in_Qt_5.6#New_Features). We can expect Qt 5.6 update [at some point in the future](https://together.jolla.com/question/76431/) and possibly QtLocation API starts to work on all devices then.

It would be interesting if you are willing and able to tinker with developer mode and command line [to install the native Maps application](https://together.jolla.com/question/136988/?answer=138143#post-id-138143) to your device and see if it pulls all the required Qt libraries we have in our Jolla 1 devices. It might fix the issue.

**Comment by mjtorn** [comment]
I use a Fairphone2 and have been _extremely_ happy with [poormaps](https://github.com/otsaloma/poor-maps) because it integrated without a hitch.

Not sure when this broke, because I haven't been updating all that often, but after going to 2.0.5.6 I have this same issue.

> Dec 10 12:54:54 Sailfish [27092]: [W] unknown:439 - file:///usr/lib/qt5/qml/Sailfish/Silica/PageStack.js:439: Error: Error while loading page: file:///usr/share/harbour-jollaopas/qml/pages/StopPage.qml:149 Type MapElement unavailable
>                                  file:///usr/share/harbour-jollaopas/qml/components/MapElement.qml:130 Type FlickableMap unavailable
>                                  file:///usr/share/harbour-jollaopas/qml/components/FlickableMap.qml:122 MySelectionDialog is not a type

(from `journalctl`)

I haven't really done this type of QML debugging (where I can't just see the results from trial and error) and don't really know where to look.

Is this solvable?

**Comment by mjtorn** [comment]
Although I have the official Jolla from before, I'd rather keep my phone as free as possible at the moment, and istr the official map app wasn't significantly better than Poormaps. So having a solution to the QML issue would be better than sidestepping the issue by installing something else than @otsaloma 's app.

**Comment by mjtorn** [comment]
Ok, it seems all the talk about the maps was a red herring that distracted me.

Apparently `MySelectionDialog.qml` may have been a file that was available but isn't anymore;

https://api.kde.org/4.12-api/kdeedu-apidocs/kanagram/html/MySelectionDialog_8qml_source.html

But the file above does not work as-is. `...MySelectionDialog.qml:100 Expected a qualified name id`

@hsarkanen would it be possible for you to implement a `MySelectionDialog.qml` and I would definitely be one to test it out?

Thanks!

**Comment by hsjpekka** [comment]
@hsarkanen I have Jolla1 and Jolla's Maps, but can't get the route map.

**Comment by hsarkanen** [comment]
Thank you @hsjpekka and @mjtorn for reporting this. Accurate information about MySelectionDialog and occurrence also on Jolla 1 made this easy to fix. This was definitely my fault and didn't have anything to do with Jolla's Map APIs.

**Comment by hsarkanen** [comment]
Actually there were another map issue with SailfishOS Haapajoki update which changes map plugin from Nokia to Here so it broke the map again. Now v0.7.2 should fix that also, but using v0.7.1 is recommended if you haven't updated yet.

**Comment by hsjpekka** [comment]
Great! Works now. Thanks!
