### ISSUE TITLE
Install fails if qt5-plugin-geoservices-here isn't installed

### ISSUE THREAD

**Issue by ZeiP** [hsarkanen/JollaOpas#21]
I tried to install JollaOpas first through Storeman (which didn't show the Install option at all) and then by downloading the RPM and selecting install, which also failed. When I tried to install the RPM manually with pkcon local-install, it showed me the actual reason: It apparently couldn't find qt5-plugin-geoservices-here:
`Fatal error: harbour-jollaopas-0.9.0-1.armv7hl requires qt5-plugin-geoservices-here, but this requirement cannot be provided`
After installing that package by running pkcon install qt5-plugin-geoservices-here, Storeman showed the install option and the package installed just fine.

Any ideas why this happened? Could there be something amiss in the RPM package which causes Storeman not to detect the dependencies properly? I'm running Sailfish 3.1.0.11 (Seitseminen).

**Comment by hsarkanen** [comment]
Jolla has had this licensing and unstable issue with QtLocation and Here Maps open for the last [6 years](https://together.jolla.com/question/80045/time-to-allow-qtpositioning-module-in-the-store/?answer=80134#post-id-80134). Apps using QtLocation are not allowed in the Jolla Store and that's why JollaOpas is not available there. Native sailfish-maps app using QtLocation is shipped with Jolla1 and is still available from Jolla Store for Jolla1, but it seems that's not [the case with later devices](https://together.jolla.com/question/173865/sailfish-maps/?answer=173872#post-id-173872).  It seems according to `pkcon depends-on sailfish-maps` that when sailfish-maps is installed the qt5-plugin-geoservices-here is installed and there should be no issue to install JollaOpas. The plugin [is listed as a dependency](https://github.com/hsarkanen/JollaOpas/blob/e894664567c4de2d50c2a1e929e2300ffdb124fd/rpm/harbour-jollaopas.yaml#L26) for the RPM and I don't know how different package managers handle those requirements and packages that may not be "officially" available to your device. Good that you found the package with pckon from some repository, but I think this is something Jolla should fix and there is nothing that could be done in JollaOpas.
