### ISSUE TITLE
[request] Reset/restore defaults in settings

### ISSUE THREAD

**Issue by bitbooster** [hsarkanen/JollaOpas#27]
Feature request: I'd like if somehow the settings page would remember the last confirmed values (from previous usage) or at least it would allow to reset values to default.
Reason: sometimes I go to settings to change some parameter but accidentally I touch a different slider than the one I'm interested to, and especially with the ones related to Change Margin/Reluctance, I don't remember how they were set (as those values are not very intuitive).

I'm not exactly sure how to implement that in a way that doesn't require too much extra code or clutter the UI, but maybe a couple of options could be:
- a pull down option for a general 'reset to defaults' of all settings
- each parameter label could show the value stored at the time the app has been launched, e.g. 'Change Margin (5 min) [3 min]' with 5 minutes current value and 3 minutes previous stored value.

**Comment by hsarkanen** [comment]
In the current implementation any history values of settings are not available since the value is overwritten every time a setting is changed e.g. slider is moved. Saving multiple versions of one setting value would be more complicated to implement and make understandable user interface for so I just implemented resetting the default values.
