### ISSUE TITLE
Save recent destinations automatically

### ISSUE THREAD

**Issue by olpeh** [hsarkanen/JollaOpas#6]
Feature request:
Automatically keep destination history and make it easy to use destinations from the history.

**Comment by hsarkanen** [comment]
Sorry for late reply and thaks for the idea.
I agree that the recent destinations should be saved automatically and provided somehow when doing new searches. Because of the long history and the amount of lecagy code in the app I think that it's not a small task to make it properly. Currently I don't have time for this but I'll implement it at some point.

**Comment by ExTechOp** [comment]
I was going to make a similar request. A shame you haven't had time to work on it lately, but thanks for the excellent application!

**Comment by hsarkanen** [comment]
Thanks for the feedback, now I had the time. Recent destinations would be found on the same dialog where favorite places are accessed. I'll upload it to openrepos.net tonight.

**Comment by olpeh** [comment]
Awesome! Seems to work. Thanks!
